### ISSUE TITLE
Support for colours in GitHub Actions does not seem to work

### ISSUE THREAD

**Issue by keattang** [bluenote10/yachalk#21]
[Reading the code](https://github.com/bluenote10/yachalk/blob/master/yachalk/supports_color.py#L51) it looks like the colour detection algorithm will short circuit and return `AllOff` if there is no TTY. 

GitHub Actions does not attach a TTY and so we will never reach [the `CI` check](https://github.com/bluenote10/yachalk/blob/master/yachalk/supports_color.py#L74).

**Comment by patrickhodelsg** [comment]
Did you find a workaround?

---
EDIT: A workaround is using the environment variables in github actions:

```yaml
    - name: Run yachart script
      env:
        FORCE_COLOR: true
      run: |
        chmod u+x script.py
        script.py
 ````
